name: polar
description: This is a Dart plugin wrapper for the Polar SDK on Android and iOS
version: 0.1.6
homepage: https://github.com/Rexios80/polar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  
  permission_handler: ^8.0.0+2
  enum_to_string: ^2.0.1
  recase: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.rexios.polar
        pluginClass: PolarPlugin
      ios:
        pluginClass: PolarPlugin